### ISSUE TITLE
Don't force CSS styles

### ISSUE THREAD

**Issue by dgsiegel** [maxshuty/accessible-web-components#1]
As the selector is embedded into a shadow root, you can't style any element from the outside. You do set some properties however which might not fit the general design of the parent site, most notably `font-weight` and `font-size`:

https://github.com/maxshuty/accessible-web-components/blob/master/src/components/simpleRange.js#L53
https://github.com/maxshuty/accessible-web-components/blob/master/src/components/simpleRange.js#L109

Would it be possible to either remove them or make them configurable via a CSS variable?

Other than the above mentioned, these might be interesting as well:

- https://github.com/maxshuty/accessible-web-components/blob/master/src/components/simpleRange.js#L62 (needs `appearance: none;`)
- https://github.com/maxshuty/accessible-web-components/blob/master/src/components/simpleRange.js#L75-L76
- https://github.com/maxshuty/accessible-web-components/blob/master/src/components/simpleRange.js#L79 (`border-width`)
- https://github.com/maxshuty/accessible-web-components/blob/master/src/components/simpleRange.js#L99 (dito)
- https://github.com/maxshuty/accessible-web-components/blob/master/src/components/simpleRange.js#L104 (dito)
- https://github.com/maxshuty/accessible-web-components/blob/master/src/components/simpleRange.js#L108 (should be auto)

**Comment by maxshuty** [comment]
@dgsiegel first off, apologies for the delayed reply. My notification settings were not set correctly on this repo.

I appreciate the input and I will make those customizable in the next release, I will try and get that out in the next few days. 

Additionally I may consider adding [CSS ::part and ::theme](https://meowni.ca/posts/part-theme-explainer/) (if `::theme` becomes a thing). That would allow you full control over the styling piercing the shadow dom.

**Update:** All of these issues have been fixed. Updating the README then will release `v1.0.5` with these fixes.

**Update 2:** Merged these. Thanks for the suggestions @dgsiegel!
