### ISSUE TITLE
Set color for slider outside of selected range?

### ISSUE THREAD

**Issue by jacobkossman** [maxshuty/accessible-web-components#10]
First of all, thank you for this! Using it in a custom Shopify theme based on Dawn and it's super helpful!

I'm wondering if there's a way to have an "active" and "inactive" type of color system? Meaning that the areas of the slider bar before and after the handles that fall outside of the selected range would be a different color than the rest of the bar.

So if you have a range slider from 0 - 100, and the current values are 25 and 50, the area of the slider bar from 0 - 24 and 51-100 would be inactive? Just for a slightly better visual representation of what is chosen.

**Comment by maxshuty** [comment]
I love this idea, it would require significant rework to this component though. This has been added to the backlog as an item to do and may be released in a future version but is not being actively developed at the moment. Thanks!
