### ISSUE TITLE
Question: Programmatically change range values?

### ISSUE THREAD

**Issue by jacobkossman** [maxshuty/accessible-web-components#11]
Is there a way with javascript to update the value(s)? For example, from a button click or another event?

**Comment by jacobkossman** [comment]
I figured out a workaround for now, by setting the "preset-min" and "preset-max" attributes with setAttribute on the range-selector. However, I think there should be a "range-set" method or something similar that could be used. Thanks!

**Comment by maxshuty** [comment]
This was completed [here](https://github.com/maxshuty/accessible-web-components/pull/19), and is available in `v.1.0.10`, thanks for the request!
