### ISSUE TITLE
Question about browser compatibility

### ISSUE THREAD

**Issue by pascalf22** [maxshuty/accessible-web-components#12]
Hi, 

Thanks for the slider, it's perfect.
Just one question.. You said that it is supported by all modern browsers, but older browser such as 2-3-4 years older(chrome, ff, edge, safari....)... will it work on those 'older' browsers ?

Thanks so much ! 

Pascal

**Comment by pavlexander** [comment]
I don't think this library is compatible with current chrome version.. On both the Opera and Edge (which are Chromium based) I see that by default with `<range-selector min-range="0" max-range="1000" />` - the page has the horizontal scrollbar on the bottom. In other words the component overflows. It needs some CSS fixes.
To add up to this issue - when moving either the left or the right slider - the other slider jitters (moves slightly back and forth). 
It seems like at some point the library was working OK, but in the current chromium (shows**115.0.5790.171** in Opera ) version it simply does not.

**Comment by maxshuty** [comment]
@pavlexander could you give me some screenshots? On the [demo](https://maxshuty.github.io/accessible-web-components/) I'm not seeing any additional horizontal scrollbar on the latest version of Chrome. Is it looking ok on Chrome for you and only happening on those other browsers? Any additional details would be great.  If you could open a separate issue that would be amazing, I'm happy to look into it and fix what I can!

@pascalf22 as far as browser support is concerned basically all modern browsers that support web components should support this, so if some how somebody is still running a super old version of, for example, Chrome then it should still work for at least 5 years back if not more.
