### ISSUE TITLE
Slider color for the right part (after the circle)

### ISSUE THREAD

**Issue by pascalf22** [maxshuty/accessible-web-components#13]
Hi ! 
Thanks a lot for this slider, i REALLY love it :)

One more thing.. is there a way to change the color of the right part of the slider (the unselected part)... i mean, at the right of the circle ?
I saw this :  slider-color="#...."  but it change both color.

Thanks so much ! 

Have a great day
Pascal

**Comment by maxshuty** [comment]
Hi there, please see [this](https://github.com/maxshuty/accessible-web-components/issues/10) issue. It's on my TODO list but not being actively developed as it is a major change to this current functionality. Thanks!
