### ISSUE TITLE
Minimum range value of '0' doesn't work

### ISSUE THREAD

**Issue by imat156** [maxshuty/accessible-web-components#14]
Due to the fallback nature of the minimum range value (https://github.com/maxshuty/accessible-web-components/blob/master/src/components/simpleRange.js#L155-L161) and the falsey nature of the integer 0, it is impossible to set the range minimum to 0. I think a different fallback check may be in order. Possibly using !isNaN to check if the parsed int is, in fact, a number, rather than relying on the truthiness of the parsed number?

**Comment by imat156** [comment]
https://jsfiddle.net/16jar39x/

**Comment by maxshuty** [comment]
Fixed [here](https://github.com/maxshuty/accessible-web-components/pull/17) and is now available in `v1.0.9` thank you for reporting this!
