### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by FelipeZago14** [maxshuty/accessible-web-components#20]
Hi, im doing exactly like the tutorial, but the EventListener function isnt triggering

**Comment by FelipeZago14** [comment]
![Screenshot_16](https://github.com/maxshuty/accessible-web-components/assets/78437618/2412b01f-7fc8-4bd0-b402-ef0da330aeab)
![Screenshot_15](https://github.com/maxshuty/accessible-web-components/assets/78437618/83217168-1252-4700-87e7-7fd126d9d4d8)
![Screenshot_14](https://github.com/maxshuty/accessible-web-components/assets/78437618/49b37f9a-d258-4c59-9513-15c04356b768)

**Comment by maxshuty** [comment]
Hi @FelipeZago14, what version are you using? Currently on the [demo](https://maxshuty.github.io/accessible-web-components/) if you open up dev tools and then change any of the sliders you can see that the event is being triggered. The code on the demo is this:

```      
document.addEventListener(
        'range-changed', 
        (event) => console.log(
          `Range has changed!
           | Slider ID (if slider has an id attribute, else it will be null): ${event.detail.sliderId}
           | Min Range selection: ${event.detail.minRangeValue.toString()} 
           | Max Range selection: ${event.detail.maxRangeValue}`
        )
 );
```

Are you placing the range selector inside of another web component or iframe and trying to add the listener somewhere that may not have "access" to that scope? Could you create a fiddle to reproduce the issue?

**Comment by maxshuty** [comment]
Hi, please open a new issue with a fiddle and steps to reproduce. Thank you!
