### ISSUE TITLE
dist asset has step=3

### ISSUE THREAD

**Issue by bnomei** [maxshuty/accessible-web-components#27]
dist asset js has step with value 3 unlike raw which has 1

https://github.com/maxshuty/accessible-web-components/blob/ea17f52784655bb4c6fd9d757de62a4a20a4a0fa/src/components/simpleRange.js#L503

**Comment by maxshuty** [comment]
Very... odd. Not sure how that happened, however I have fixed that in the latest version `v1.0.14` [here](https://github.com/maxshuty/accessible-web-components/commit/750aee4da17267894e796e3f2d37cbaeb7a329c0). Thanks for reporting!
