### ISSUE TITLE
Add opacity / disabled effect to slider part which is out of range

### ISSUE THREAD

**Issue by frankykubo** [maxshuty/accessible-web-components#28]
Hello,

first thing, great package! Simple and effective. I have just one thing which came up to my mind when looking and trying it:

It would be really nice if the parts, which are out of range, would have some sort of opacity added to show user that that part is not currently selected.

On the image, the parts i am talking about are highlighted with yellow underline:

![image](https://github.com/maxshuty/accessible-web-components/assets/50501921/0c58c422-2004-4fdd-8125-10c06c356035)

Thank you for your answer.

**Comment by maxshuty** [comment]
Hi @frankykubo, thank you for the feedback! Unfortunately the way that this is setup is actually two different range inputs right next to one another to give the appearance of a single range selector input. This means that I cannot style only the yellow portions from your image above, I could instead style the left half or the right half of the range selectors, but not what is "outside" of the range.
